apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: exercises
  name: postgres-stset
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres
          image: postgres:14.18
          ports:
            - name: web
              containerPort: 6379
          volumeMounts:
            - name: postgres-data-storage
              mountPath: /data
          env:
            - name: POSTGRES_USER
              value: "postgres-user"
            - name: POSTGRES_PASSWORD
              value: "postgres-password"
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-storage
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 100Mi


---
apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: postgres-svc
  labels:
    app: postgres-app
spec:
  ports:
  - port: 6379
    name: web
  clusterIP: None
  selector:
    app: postgres-app