apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/service.yaml
  - todo-app/manifests/ingress.yaml
  - todo-app/manifests/cronjob.yaml
  - todo-app/volumes/persistentvolumeclaim.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-backend/manifests/configmap.yaml
  - todo-backend/manifests/statefulset.yaml
images:
  - name: TODO-PROJECT/FRONTEND-IMAGE
    newName: juhanikat/replaced-by-github-actions
  - name: TODO-PROJECT/BACKEND-IMAGE
    newName: juhanikat/replaced-by-github-actions